name: Build and Publish Docker Image

on:
  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:headless

      - name: Get version from package.json
        id: extract-version
        run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/vlp-frontend-angular
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.VERSION }}
            type=sha,format=long
          labels: |
            org.opencontainers.image.title=VLP Frontend Angular
            org.opencontainers.image.description=Virtual Learning Platform frontend application
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.authors=Ivan Simeonov ivannicksimeonov@gmail.com
            org.opencontainers.image.category=application
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.created=${{ steps.meta.outputs.date }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
